### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by elig-45** [HugoJF/game-hosting-panel#12]
Hey. Does this work with Pterodactyl 1.X ?

**Comment by HugoJF** [comment]
I'm not sure, this was developed and tested only for 0.7. I have no idea if anything broke after the update.

But since then I haven't had the time (or motivation) to keep this project up-do-date with Pterodactyl.

**Comment by The-MG** [comment]
Only a few things that would have to be changed. Such as server creation.

**Comment by HugoJF** [comment]
> Only a few things that would have to be changed. Such as server creation.

I figured it would be somewhat straight forward.

The main reason I'm not currently updating the project is because since I don't rent dedicated servers directly anymore, I have no reason to keep this project as it is currently.

I'm trying to figure out the best way to turn this into a SaaS, where I can host this myself with a complete billing system (PayPal, MercadoPago, and other providers here in Brazil) where you just need provide your Pterodactyl Panel API credentials and everything is ready to go, and still keep everything else (server creation, user management, permission management, parameter configuration, etc etc) open-source and STILL usable by server admins.

I had quite alot of people asking me for something like this and I figured that would be the best way to keep development open-source and give me some incentive to keep it active.

THAT BEING SAID: I'll probably only return to this project by the end of the year.

**Comment by The-MG** [comment]
Well, I've had many interests in this panel as-well. I've tried to update it to the most recent stuff so you don't get errors when trying to php artisan start, or compser install within a command line. I would be really interested in helping with this project if I can find out how you store some of your things. It'd also help if you updated the Pterodactyl API package you are using to the latest version which supports Pterodactyl v1. If you need help with that, I help develop the HCGCloud API (which is the one being used) so it'll be easy for me to help you get that updated.  I've made a few client areas for free hosts including my own, and I'm just now starting to get into paid hosting client areas.

**Comment by theMackabu** [comment]
This seems like a very cool project in my eyes too

**Comment by HugoJF** [comment]
> Well, I've had many interests in this panel as-well. I've tried to update it to the most recent stuff so you don't get errors when trying to php artisan start, or compser install within a command line. I would be really interested in helping with this project if I can find out how you store some of your things. It'd also help if you updated the Pterodactyl API package you are using to the latest version which supports Pterodactyl v1. If you need help with that, I help develop the HCGCloud API (which is the one being used) so it'll be easy for me to help you get that updated. I've made a few client areas for free hosts including my own, and I'm just now starting to get into paid hosting client areas.

If you could point the main changes from 0.7 to 1.0 that I should be looking for, that would make things alot quicker. But as I said, I didn't plan to update this panel at all, but since alot of people are interested in this, I'm trying to get my personal projects up to date before going back to this.

Also, since I'm planning on turning this project into a SaaS, there a big chance any pull request I receive will be ignored (aside from the core stuff that handles Pterodactyl communication).

I'm open to feedback for new features (integrated console, 2FA, social login, etc) feel free to open new issues, that way once I get back to this, I can easily track them.

**Comment by theMackabu** [comment]
Nice, sounds good!

**Comment by The-MG** [comment]
> > Well, I've had many interests in this panel as-well. I've tried to update it to the most recent stuff so you don't get errors when trying to php artisan start, or compser install within a command line. I would be really interested in helping with this project if I can find out how you store some of your things. It'd also help if you updated the Pterodactyl API package you are using to the latest version which supports Pterodactyl v1. If you need help with that, I help develop the HCGCloud API (which is the one being used) so it'll be easy for me to help you get that updated. I've made a few client areas for free hosts including my own, and I'm just now starting to get into paid hosting client areas.
> 
> 
> 
> If you could point the main changes from 0.7 to 1.0 that I should be looking for, that would make things alot quicker. But as I said, I didn't plan to update this panel at all, but since alot of people are interested in this, I'm trying to get my personal projects up to date before going back to this.
> 
> 
> 
> Also, since I'm planning on turning this project into a SaaS, there a big chance any pull request I receive will be ignored (aside from the core stuff that handles Pterodactyl communication).
> 
> 
> 
> I'm open to feedback for new features (integrated console, 2FA, social login, etc) feel free to open new issues, that way once I get back to this, I can easily track them.

As far as I know, just server creation. Haven't had time to look through all of your code yet. When I get back to my office I will do that though!!

**Comment by theMackabu** [comment]
> > Well, I've had many interests in this panel as-well. I've tried to update it to the most recent stuff so you don't get errors when trying to php artisan start, or compser install within a command line. I would be really interested in helping with this project if I can find out how you store some of your things. It'd also help if you updated the Pterodactyl API package you are using to the latest version which supports Pterodactyl v1. If you need help with that, I help develop the HCGCloud API (which is the one being used) so it'll be easy for me to help you get that updated. I've made a few client areas for free hosts including my own, and I'm just now starting to get into paid hosting client areas.
> 
> If you could point the main changes from 0.7 to 1.0 that I should be looking for, that would make things alot quicker. But as I said, I didn't plan to update this panel at all, but since alot of people are interested in this, I'm trying to get my personal projects up to date before going back to this.
> 
> Also, since I'm planning on turning this project into a SaaS, there a big chance any pull request I receive will be ignored (aside from the core stuff that handles Pterodactyl communication).
> 
> I'm open to feedback for new features (integrated console, 2FA, social login, etc) feel free to open new issues, that way once I get back to this, I can easily track them.

Would this new SaaS include the billing system too?

**Comment by HugoJF** [comment]
> > > Well, I've had many interests in this panel as-well. I've tried to update it to the most recent stuff so you don't get errors when trying to php artisan start, or compser install within a command line. I would be really interested in helping with this project if I can find out how you store some of your things. It'd also help if you updated the Pterodactyl API package you are using to the latest version which supports Pterodactyl v1. If you need help with that, I help develop the HCGCloud API (which is the one being used) so it'll be easy for me to help you get that updated. I've made a few client areas for free hosts including my own, and I'm just now starting to get into paid hosting client areas.
> > 
> > 
> > If you could point the main changes from 0.7 to 1.0 that I should be looking for, that would make things alot quicker. But as I said, I didn't plan to update this panel at all, but since alot of people are interested in this, I'm trying to get my personal projects up to date before going back to this.
> > Also, since I'm planning on turning this project into a SaaS, there a big chance any pull request I receive will be ignored (aside from the core stuff that handles Pterodactyl communication).
> > I'm open to feedback for new features (integrated console, 2FA, social login, etc) feel free to open new issues, that way once I get back to this, I can easily track them.
> 
> Would this new SaaS include the billing system too?

Yes, that would be the only difference (in terms of code) from this repository. I don't plan on handicap this repository in order to push a paid product (like removing features, adding closed-source features, etc). The plan is to provide a complete solution to server owners that want to sell their extra capacity with ease (minimal to no modifications needed) or expand their business with more servers.

I like to think this project will still have lots of value even without the billing system (providing ease to use API to create servers, implement some kind of point system, add your own billing system, limited time free servers, and some other features I have planned, a better way to handle multiple nodes).

That said, I'm yet to fully decide what I really want to do. It will depend on how much time I'll have in hands.

**Comment by theMackabu** [comment]
I would pay for a dedicated gameserver billing system, instead of using whmcs, which is a pain to configure with pterodactyl

**Comment by The-MG** [comment]
Hey Hugo! Haven't heard from you in a while. If you have any updates or need any help let me know!

**Comment by HugoJF** [comment]
Hello, I've been working fulltime since the last update and I'm trying to get this project to become my final project for my graduation. That way I can take 2 birds with one stone.

In the mean time I've also documented most features I plan on adding to the project, and started creating a roadmap for this project. The mercado-escola repository is becoming my playground for the time being, I'm exploring a few techniques and tools I've learned in the last few months that I plan on using here. 

The current plan is split this into 2 projects (frontend and backend), that way I can focus on a solid API and maximize the UX without mixing the code or making the project huge. That also allows users to only use the API an integrate it into other things (Discord bots, existing dashboards, other APIs, etc). I'll also update this project to become a Serverless AWS application, that way I can minimize any infrastructure problem I might have in the future (that was the biggest pain I had with other projects) and also provide the best performance possible. Of course Laravel and React will still be my tech-stack of choice. The only thing I still need to think about is how the open-source and the hosted version will differ.

While I can't really give an estimate for when I'll start, when I'll finish, what I'll do, I can assure that this project WILL be actively developed again.

**Comment by The-MG** [comment]
> Hello, I've been working fulltime since the last update and I'm trying to get this project to become my final project for my graduation. That way I can take 2 birds with one stone.
> 
> In the mean time I've also documented most features I plan on adding to the project, and started creating a roadmap for this project. The mercado-escola repository is becoming my playground for the time being, I'm exploring a few techniques and tools I've learned in the last few months that I plan on using here.
> 
> The current plan is split this into 2 projects (frontend and backend), that way I can focus on a solid API and maximize the UX without mixing the code or making the project huge. That also allows users to only use the API an integrate it into other things (Discord bots, existing dashboards, other APIs, etc). I'll also update this project to become a Serverless AWS application, that way I can minimize any infrastructure problem I might have in the future (that was the biggest pain I had with other projects) and also provide the best performance possible. Of course Laravel and React will still be my tech-stack of choice. The only thing I still need to think about is how the open-source and the hosted version will differ.
> 
> While I can't really give an estimate for when I'll start, when I'll finish, what I'll do, I can assure that this project WILL be actively developed again.

Nice to hear an update from you! Sounds like you have a long road ahead of you!

**Comment by tahaluindo** [comment]
good

**Comment by NellyOfc** [comment]
hello, I wanted to know if they gave up on the project, they haven't updated it for 2 years, I was interested in the panel, and I decided to install it but I was unsuccessful because it was up to date, could you clarify this doubt if you are going to continue with the project or if you are going to give up on it ?

**Comment by HugoJF** [comment]
I did not give up on this project yet and I'm still trying to allocate some time to it. I'm trying to fit it as a final graduation project, that way I don't have to waste my free time with another useless university project. I'll have a more definitive answer in the next ~3 months.

While I don't want to abandon it, given how much traffic it still has for a project that is 2 years without any updates, I also don't want to half-ass support it, that's why it taking a bit longer than I planned initially.

**Comment by JohnB17** [comment]
The readme in this repo says payment-system is not open source and you need your own payment system, is this it? [https://github.com/HugoJF/payment-system](https://github.com/HugoJF/payment-system)

**Comment by HugoJF** [comment]
> The readme in this repo says payment-system is not open source and you need your own payment system, is this it? https://github.com/HugoJF/payment-system

Yes, it wasn't planned to be open-source at the time, but I decided to change it to public since I'm not using it anymore, I have absolutely 0 documentation on it and it has a lot of harded code parameters.
