### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by BasToTheMax** [HugoJF/game-hosting-panel#17]
How to install this?
I already have an pterodactyl panel 0.7 :)

**Comment by HugoJF** [comment]
I'm sorry, but I'm currently unable to continue developing this project and because of that I haven't found the time to write proper install instructions.

I have new plans for this panel and I plan on starting them this year. And because of that I'll most likely update the project to Pterodactyl 1.0 and redefine the scope of the project before writing install instructions.
