### ISSUE TITLE
How i can entry to admin panel?

### ISSUE THREAD

**Issue by Mauri35** [HugoJF/game-hosting-panel#25]
I'm sorry for my ingorance but I don't understand how it works perfectly, I installed everything well but when creating a server I did not see any game or location, seeing the code I assumed that it has an admin panel but I don't know how to access it

**Comment by HugoJF** [comment]
I'm sorry, the documentation on this project is pretty out-dated by now, and I really don't have the time to update them.

Games and locations are synced from Pterodactyl's API by a command that I think is automatically ran by the scheduler.

Since this issue will not be relevant for future releases (as I plan on re-writing a big chunk of this project), I'll be closing the issue. Feel free to still ask me anything.
