### ISSUE TITLE
Will your panel support Pterodactyl 1.0?

### ISSUE THREAD

**Issue by MrFallen** [HugoJF/game-hosting-panel#8]
Hello. Your panel so awesome! Will your panel support Pterodactyl 1.0?

**Comment by HugoJF** [comment]
Probably not, at least I'm not doing it soon.

That's the main reason I decided to release to the public. It's a 4 month project that unfortunately I'll not have time to really put it to use. And since my CS:GO community servers started getting less popular, I don't really have reason to keep maintaining this project.

That said, I'll still clean some really rough corners in my free time.

**Comment by MrFallen** [comment]
I wanna be used your project in my hosting in Russia. Can i use?

**Comment by HugoJF** [comment]
Sure, feel free to use this project commercially.
